server:
  port: 8080
spring:
  datasource:
    name: mall_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root123
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 60000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.szz.mall.api.entity

logging:
  config: classpath:logback-dev.xml